---
abstract: 'Locale::TextDomain::OO::Extract - Extracts internationalization data as gettext pot file'
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
build_requires:
  Cwd: '0'
  Test::Differences: '0.60'
  Test::Exception: '0'
  Test::More: '0'
  Test::NoWarnings: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4206, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Locale-TextDomain-OO-Extract
provides:
  Locale::TextDomain::OO::Extract:
    file: lib/Locale/TextDomain/OO/Extract.pm
    version: '2.003'
  Locale::TextDomain::OO::Extract::Base::RegexBasedExtractor:
    file: lib/Locale/TextDomain/OO/Extract/Base/RegexBasedExtractor.pm
    version: '2.000'
  Locale::TextDomain::OO::Extract::HTML:
    file: lib/Locale/TextDomain/OO/Extract/HTML.pm
    version: '2.002'
  Locale::TextDomain::OO::Extract::JavaScript:
    file: lib/Locale/TextDomain/OO/Extract/JavaScript.pm
    version: '2.002'
  Locale::TextDomain::OO::Extract::Perl:
    file: lib/Locale/TextDomain/OO/Extract/Perl.pm
    version: '2.002'
  Locale::TextDomain::OO::Extract::Process:
    file: lib/Locale/TextDomain/OO/Extract/Process.pm
    version: '2.002'
  Locale::TextDomain::OO::Extract::Process::Plugin::MO:
    file: lib/Locale/TextDomain/OO/Extract/Process/Plugin/MO.pm
    version: '2.003'
  Locale::TextDomain::OO::Extract::Process::Plugin::PO:
    file: lib/Locale/TextDomain/OO/Extract/Process/Plugin/PO.pm
    version: '2.003'
  Locale::TextDomain::OO::Extract::Role::File:
    file: lib/Locale/TextDomain/OO/Extract/Role/File.pm
    version: '2.002'
  Locale::TextDomain::OO::Extract::TT:
    file: lib/Locale/TextDomain/OO/Extract/TT.pm
    version: '2.002'
recommends:
  Test::Pod: '1.14'
  Test::Pod::Coverage: '1.04'
requires:
  Carp: '0'
  Class::Load: '0'
  Clone: '0'
  Data::Dumper: '0'
  Encode: '0'
  Locale::MO::File: '0.05'
  Locale::TextDomain::OO::Util: '3.001'
  Moo: '1.003001'
  MooX::StrictConstructor: '0'
  MooX::Types::MooseLike: '0'
  Path::Tiny: '0'
  Set::Scalar: '0'
  namespace::autoclean: '0'
  perl: '5.009005'
resources:
  license: http://dev.perl.org/licenses/
version: '2.003'
